# GENERAL
server:
  port: 8081


# DATABASE
spring:
  datasource:
    url: jdbc:mysql://localhost/todoapp?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    dbname: todoapp
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false


  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher